import { Product } from '../types';

export const products: Product[] = [
	{
		id: 'prod-1',
		category: ['Men', 'Long Sleeve', 'Slim Fit'],
		title: 'Formal Dress Shirts Casual Long Sleeve Slim Fit',
		isBestSeller: true,
		variants: [
			{
				id: 'var-1123',
				size: 'XS',
				color: 'blue',
				price: '$25',
				stock: 0,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1WgrMrPFzJuPJOclniif2V5njnxnVi2La',
			},
			{
				id: 'var-1',
				size: 'S',
				color: 'blue',
				price: '$25',
				stock: 165,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1WgrMrPFzJuPJOclniif2V5njnxnVi2La',
			},
			{
				id: 'var-2',
				size: 'M',
				color: 'blue',
				price: '$25',
				stock: 183,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1WgrMrPFzJuPJOclniif2V5njnxnVi2La',
			},
			{
				id: 'var-3',
				size: 'L',
				color: 'blue',
				price: '$25',
				stock: 125,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1WgrMrPFzJuPJOclniif2V5njnxnVi2La',
			},
			{
				id: 'var-4',
				size: 'XS',
				color: 'black',
				price: '$25',
				stock: 267,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1cI30IA_vu9H91H22RQATPWNGXHqNz0Fm',
			},
			{
				id: 'var-5',
				size: 'M',
				color: 'black',
				price: '$25',
				stock: 123,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1cI30IA_vu9H91H22RQATPWNGXHqNz0Fm',
			},
			{
				id: 'var-6',
				size: 'XL',
				color: 'black',
				price: '$25',
				stock: 66,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1cI30IA_vu9H91H22RQATPWNGXHqNz0Fm',
			},
			{
				id: 'var-7',
				size: 'S',
				color: 'violet',
				price: '$25',
				stock: 99,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1U-PzTUYyr9WO3Jm61kEk1S197ho5G7oW',
			},
			{
				id: 'var-8',
				size: 'M',
				color: 'violet',
				price: '$25',
				stock: 154,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1U-PzTUYyr9WO3Jm61kEk1S197ho5G7oW',
			},
			{
				id: 'var-9',
				size: 'L',
				color: 'violet',
				price: '$25',
				stock: 153,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1U-PzTUYyr9WO3Jm61kEk1S197ho5G7oW',
			},
			{
				id: 'var-91',
				size: 'XL',
				color: 'violet',
				price: '$25',
				stock: 0,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1U-PzTUYyr9WO3Jm61kEk1S197ho5G7oW',
			},
		],
	},
	{
		id: 'prod-2',
		category: ['Unisex', 'Short Sleeve', 'Slim Fit'],
		title: 'Formal Dress Shirts Casual Short Sleeve Slim Fit',
		isBestSeller: false,
		variants: [
			{
				id: 'var-10',
				size: 'XS',
				color: 'blue',
				price: '$35',
				stock: 0,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1ueZZRohN-q1BYKPo1kwD2uO5apQowpI3',
			},
			{
				id: 'var-101',
				size: 'S',
				color: 'blue',
				price: '$35',
				stock: 152,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1ueZZRohN-q1BYKPo1kwD2uO5apQowpI3',
			},
			{
				id: 'var-11',
				size: 'M',
				color: 'blue',
				price: '$35',
				stock: 133,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1ueZZRohN-q1BYKPo1kwD2uO5apQowpI3',
			},
			{
				id: 'var-12',
				size: 'XL',
				color: 'blue',
				price: '$35',
				stock: 55,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1ueZZRohN-q1BYKPo1kwD2uO5apQowpI3',
			},
			{
				id: 'var-13',
				size: 'S',
				color: 'gray',
				price: '$35',
				stock: 55,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1Bd79JX0zimhYe3BttEBo79fCu2DrQLnr',
			},
			{
				id: 'var-14',
				size: 'M',
				color: 'gray',
				price: '$35',
				stock: 167,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1Bd79JX0zimhYe3BttEBo79fCu2DrQLnr',
			},
			{
				id: 'var-15',
				size: 'X',
				color: 'gray',
				price: '$35',
				stock: 176,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1Bd79JX0zimhYe3BttEBo79fCu2DrQLnr',
			},
			{
				id: 'var-16',
				size: 'XL',
				color: 'gray',
				price: '$35',
				stock: 129,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1Bd79JX0zimhYe3BttEBo79fCu2DrQLnr',
			},
		],
	},
	{
		id: 'prod-3',
		category: ['Unisex', 'Short', 'Slim Fit', 'Summer'],
		title: 'Soft Summer Short Slim Fit',
		isBestSeller: true,
		variants: [
			{
				id: 'var-17',
				size: 'S',
				color: 'gray',
				price: '$20',
				stock: 212,
				discount: '0%',
				image: 'https://drive.google.com/uc?id=10c_VhHRWPcbcdKmOtCSoOnX_kPEoHnF2',
			},
			{
				id: 'var-18',
				size: 'M',
				color: 'gray',
				price: '$20',
				stock: 166,
				discount: '0%',
				image: 'https://drive.google.com/uc?id=10c_VhHRWPcbcdKmOtCSoOnX_kPEoHnF2',
			},
			{
				id: 'var-19',
				size: 'L',
				color: 'gray',
				price: '$20',
				stock: 155,
				discount: '0%',
				image: 'https://drive.google.com/uc?id=10c_VhHRWPcbcdKmOtCSoOnX_kPEoHnF2',
			},
			{
				id: 'var-20',
				size: 'S',
				color: 'pink',
				price: '$20',
				stock: 167,
				discount: '0%',
				image: 'https://drive.google.com/uc?id=1eiwHYi0xZgr0SsMeF9FYmxEF0BIJk_ib',
			},
			{
				id: 'var-21',
				size: 'M',
				color: 'pink',
				price: '$20',
				stock: 132,
				discount: '0%',
				image: 'https://drive.google.com/uc?id=1eiwHYi0xZgr0SsMeF9FYmxEF0BIJk_ib',
			},
		],
	},
	{
		id: 'prod-4',
		category: ['Women', 'Polo', 'Dress'],
		title: 'Icy Blue Polo Dress',
		isBestSeller: false,
		variants: [
			{
				id: 'var-22',
				size: 'S',
				color: 'blue',
				price: '$45',
				stock: 23,
				discount: '5%',
				image: 'https://drive.google.com/uc?id=1Qlci-y6N6hvZa_euIpSzBb9JYMOMElkH',
			},
			{
				id: 'var-23',
				size: 'M',
				color: 'blue',
				price: '$45',
				stock: 155,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1Qlci-y6N6hvZa_euIpSzBb9JYMOMElkH',
			},
			{
				id: 'var-24',
				size: 'L',
				color: 'blue',
				price: '$45',
				stock: 177,
				discount: '$10',
				image: 'https://drive.google.com/uc?id=1Qlci-y6N6hvZa_euIpSzBb9JYMOMElkH',
			},
		],
	},
	{
		id: 'prod-5',
		category: ['Women', 'Dress'],
		title: 'Tiered Wave Shirt Dress',
		isBestSeller: false,
		variants: [
			{
				id: 'var-25',
				size: 'S',
				color: 'navy & white',
				price: '$55',
				stock: 67,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1ggvVczg_tOE-Z9BBCHv2QRIveVT_0lDP',
			},
			{
				id: 'var-26',
				size: 'M',
				color: 'navy & white',
				price: '$55',
				stock: 55,
				discount: '$5',
				image: 'https://drive.google.com/uc?id=1ggvVczg_tOE-Z9BBCHv2QRIveVT_0lDP',
			},
			{
				id: 'var-27',
				size: 'L',
				color: 'navy & white',
				price: '$55',
				stock: 100,
				discount: '15%',
				image: 'https://drive.google.com/uc?id=1ggvVczg_tOE-Z9BBCHv2QRIveVT_0lDP',
			},
		],
	},
];

export const productFilter = {
	gender: ['Men', 'Women', 'Unisex'],
	category: [
		'Long Sleeve',
		'Slim Fit',
		'Short Sleeve',
		'Short',
		'Summer',
		'Polo',
		'Dress',
	],
	trends: ['Best Seller', 'Hot This Month'],
};

export const cartItems = [
	{
		_id: '1',
		userId: 'U1',
		productId: 'prod-1',
		variantId: 'var-1',
		title: 'Formal Dress Shirts Casual Long Sleeve Slim Fit',
		size: 'L',
		color: 'blue',
		quantity: 2,
		price: 25,
		isFreeShipping: false,
		image: 'https://www.kasandbox.org/programming-images/avatars/leaf-blue.png',
		isPaymentComplete: false,
	},
	{
		_id: '2',
		userId: 'U1',
		productId: 'prod-2',
		variantId: 'var-1',
		title: 'Formal Dress Shirts Casual Long Sleeve Slim Fit',
		size: 'L',
		color: 'blue',
		quantity: 2,
		price: 25,
		isFreeShipping: false,
		image: 'https://www.kasandbox.org/programming-images/avatars/leaf-blue.png',
		isPaymentComplete: false,
	},
];
